#!/usr/bin/python
from subprocess import call


def clone_repo(url, path):
    command = 'git clone {url} {path}'.format(url=url, path=path)
    call(command.split(' '))


repos = []

for repo in repos:
    clone_repo(url=repo[0], path=repo[1])
